services:
  nookly:
    image: ghcr.io/morina8700/nookly:latest
    restart: unless-stopped
    ports:
      - "8001:8001"

    labels:
      com.centurylinklabs.watchtower.enable: "true"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost:8001 | grep -qE '^[2-4][0-9][0-9]$'"
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s

  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_CLEANUP: "true"
    command: --label-enable
