// <auto-generated />
using System;
using BookMyHome.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMyHome.Persistence.Migrations
{
    [DbContext(typeof(BookMyHomeDbContext))]
    [Migration("20260924110157_AddAccommodationPropertyDetails")]
    partial class AddAccommodationPropertyDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMyHome.Domain.Models.Accommodation", b =>
                {
                    b.Property<Guid>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FloorAreaSquareMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasAirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBalcony")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHeatedFloors")
                        .HasColumnType("bit");

                    b.Property<bool>("HasKitchen")
                        .HasColumnType("bit");

                    b.Property<bool>("HasParking")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPool")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTv")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWasher")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("bit");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SmokingAllowed")
                        .HasColumnType("bit");

                    b.HasKey("AccommodationId");

                    b.HasIndex("HostId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Beach Road 1",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            Description = "Hyggeligt sommerhus tæt på stranden med stor terrasse, lys stue og moderne køkken.",
                            FloorAreaSquareMeters = 92m,
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasHeatedFloors = true,
                            HasKitchen = true,
                            HasParking = true,
                            HasPool = false,
                            HasTv = true,
                            HasWasher = true,
                            HasWifi = true,
                            HostId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MaxGuests = 6,
                            Name = "Beach House",
                            PetsAllowed = true,
                            PricePerNight = 1200m,
                            SmokingAllowed = false
                        },
                        new
                        {
                            AccommodationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Main Street 10",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            Description = "",
                            FloorAreaSquareMeters = 58m,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHeatedFloors = false,
                            HasKitchen = true,
                            HasParking = false,
                            HasPool = false,
                            HasTv = true,
                            HasWasher = true,
                            HasWifi = true,
                            HostId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MaxGuests = 4,
                            Name = "City Apartment",
                            PetsAllowed = false,
                            PricePerNight = 850m,
                            SmokingAllowed = false
                        });
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.AccommodationImage", b =>
                {
                    b.Property<Guid>("AccommodationImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccommodationImageId");

                    b.HasIndex("AccommodationId");

                    b.ToTable("AccommodationImages");

                    b.HasData(
                        new
                        {
                            AccommodationImageId = new Guid("10000000-0000-0000-0000-000000000001"),
                            AccommodationId = new Guid("a09af322-d431-4be3-b01a-d7a444355088"),
                            ImageUrl = "/Images/SommerHus1/Nova-idyll-facade.jpg"
                        },
                        new
                        {
                            AccommodationImageId = new Guid("10000000-0000-0000-0000-000000000002"),
                            AccommodationId = new Guid("a09af322-d431-4be3-b01a-d7a444355088"),
                            ImageUrl = "/Images/SommerHus1/Nova-idyll-facade-terrasse.jpg"
                        },
                        new
                        {
                            AccommodationImageId = new Guid("10000000-0000-0000-0000-000000000003"),
                            AccommodationId = new Guid("a09af322-d431-4be3-b01a-d7a444355088"),
                            ImageUrl = "/Images/SommerHus1/Nova-idyll-inde-alrum.jpg"
                        },
                        new
                        {
                            AccommodationImageId = new Guid("10000000-0000-0000-0000-000000000004"),
                            AccommodationId = new Guid("a09af322-d431-4be3-b01a-d7a444355088"),
                            ImageUrl = "/Images/SommerHus1/Nova-idyll-inde-stue.jpg"
                        },
                        new
                        {
                            AccommodationImageId = new Guid("10000000-0000-0000-0000-000000000005"),
                            AccommodationId = new Guid("a09af322-d431-4be3-b01a-d7a444355088"),
                            ImageUrl = "/Images/SommerHus1/Nova-idyll-inde-stue-kurvesofa.jpg"
                        },
                        new
                        {
                            AccommodationImageId = new Guid("10000000-0000-0000-0000-000000000006"),
                            AccommodationId = new Guid("a09af322-d431-4be3-b01a-d7a444355088"),
                            ImageUrl = "/Images/SommerHus1/Nova-idyll-inde-stue-sofa.jpg"
                        },
                        new
                        {
                            AccommodationImageId = new Guid("10000000-0000-0000-0000-000000000007"),
                            AccommodationId = new Guid("a09af322-d431-4be3-b01a-d7a444355088"),
                            ImageUrl = "/Images/SommerHus1/Nova-idyll-inde-stue-udgang-terrasse.jpg"
                        },
                        new
                        {
                            AccommodationImageId = new Guid("10000000-0000-0000-0000-000000000008"),
                            AccommodationId = new Guid("a09af322-d431-4be3-b01a-d7a444355088"),
                            ImageUrl = "/Images/SommerHus1/Nova-idyll-plan.png"
                        });
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("BookingId");

                    b.HasIndex("AccommodationId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AccommodationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndDate = new DateOnly(2027, 6, 5),
                            StartDate = new DateOnly(2027, 6, 1)
                        },
                        new
                        {
                            BookingId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AccommodationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndDate = new DateOnly(2027, 7, 15),
                            StartDate = new DateOnly(2027, 7, 10)
                        });
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Host", b =>
                {
                    b.HasBaseType("BookMyHome.Domain.Models.User");

                    b.HasDiscriminator().HasValue("Host");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "host@bookmyhome.dk",
                            Name = "Test Host"
                        });
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Accommodation", b =>
                {
                    b.HasOne("BookMyHome.Domain.Models.Host", "Host")
                        .WithMany("Accommodations")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.AccommodationImage", b =>
                {
                    b.HasOne("BookMyHome.Domain.Models.Accommodation", "Accommodation")
                        .WithMany("Images")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Booking", b =>
                {
                    b.HasOne("BookMyHome.Domain.Models.Accommodation", "Accommodation")
                        .WithMany("Bookings")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Accommodation", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Host", b =>
                {
                    b.Navigation("Accommodations");
                });
#pragma warning restore 612, 618
        }
    }
}
